name: Create a package
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
        
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/advanced-action-robot-framework-*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging        
      - uses: ncipollo/release-action@v1
        with:
          tag: "v0.1.1"
          artifacts: "staging/advanced-action-robot-framework-*.jar,robot/listener/*.py"
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.TOKEN }}
